global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  receiver: 'email_notification'

receivers:
- name: 'email_notification'
  email_configs:
  - to: 'abhradipserampore@gmail.com'
    from: 'abhradipserampore@gmail.com'
   # google mail server
    smarthost: smtp.gmail.com:587
    auth_username: 'abhradipserampore@gmail.com'
    auth_identity: 'abhradipserampore@gmail.com'
    auth_password: 'rivi upam nyhw zvbq'
    headers :
      Subject: 'Highly urgent .. .Please look ASAP !! '
    text: '{ { . CommonAnnotations. summary } } '